export const MOROCCO_LOCATIONS = [
  // Aéroports
  { type: 'Aéroport', name: 'Aéroport Mohammed V', city: 'Casablanca', icon: '✈️' },
  { type: 'Aéroport', name: 'Aéroport Marrakech Menara', city: 'Marrakech', icon: '✈️' },
  { type: 'Aéroport', name: 'Aéroport Fès-Saïss', city: 'Fès', icon: '✈️' },
  { type: 'Aéroport', name: 'Aéroport Agadir Al Massira', city: 'Agadir', icon: '✈️' },
  { type: 'Aéroport', name: 'Aéroport Tanger Ibn Battouta', city: 'Tanger', icon: '✈️' },
  { type: 'Aéroport', name: 'Aéroport Rabat-Salé', city: 'Rabat', icon: '✈️' },
  { type: 'Aéroport', name: 'Aéroport Oujda Angads', city: 'Oujda', icon: '✈️' },
  { type: 'Aéroport', name: 'Aéroport Essaouira Mogador', city: 'Essaouira', icon: '✈️' },
  { type: 'Aéroport', name: 'Aéroport Ouarzazate', city: 'Ouarzazate', icon: '✈️' },
  { type: 'Aéroport', name: 'Aéroport Nador El Aroui', city: 'Nador', icon: '✈️' },
  { type: 'Aéroport', name: 'Aéroport Tétouan Saniat Rmel', city: 'Tétouan', icon: '✈️' },
  { type: 'Aéroport', name: 'Aéroport Laâyoune Hassan I', city: 'Laâyoune', icon: '✈️' },
  // Gares
  { type: 'Gare', name: 'Gare Casa Voyageurs', city: 'Casablanca', icon: '🚂' },
  { type: 'Gare', name: 'Gare Casa Port', city: 'Casablanca', icon: '🚂' },
  { type: 'Gare', name: 'Gare Marrakech', city: 'Marrakech', icon: '🚂' },
  { type: 'Gare', name: 'Gare Rabat Ville', city: 'Rabat', icon: '🚂' },
  { type: 'Gare', name: 'Gare Rabat Agdal', city: 'Rabat', icon: '🚂' },
  { type: 'Gare', name: 'Gare Fès', city: 'Fès', icon: '🚂' },
  { type: 'Gare', name: 'Gare Tanger Ville', city: 'Tanger', icon: '🚂' },
  { type: 'Gare', name: 'Gare Meknès', city: 'Meknès', icon: '🚂' },
  { type: 'Gare', name: 'Gare Oujda', city: 'Oujda', icon: '🚂' },
  { type: 'Gare', name: 'Gare Kénitra', city: 'Kénitra', icon: '🚂' },
  { type: 'Gare', name: 'Gare Tanger Med', city: 'Tanger', icon: '🚂' },
  // Villes
  { type: 'Ville', name: 'Casablanca', city: 'Casablanca', icon: '📍' },
  { type: 'Ville', name: 'Marrakech', city: 'Marrakech', icon: '📍' },
  { type: 'Ville', name: 'Rabat', city: 'Rabat', icon: '📍' },
  { type: 'Ville', name: 'Fès', city: 'Fès', icon: '📍' },
  { type: 'Ville', name: 'Tanger', city: 'Tanger', icon: '📍' },
  { type: 'Ville', name: 'Agadir', city: 'Agadir', icon: '📍' },
  { type: 'Ville', name: 'Meknès', city: 'Meknès', icon: '📍' },
  { type: 'Ville', name: 'Oujda', city: 'Oujda', icon: '📍' },
  { type: 'Ville', name: 'Essaouira', city: 'Essaouira', icon: '📍' },
  { type: 'Ville', name: 'Ouarzazate', city: 'Ouarzazate', icon: '📍' },
  { type: 'Ville', name: 'Chefchaouen', city: 'Chefchaouen', icon: '📍' },
  { type: 'Ville', name: 'Dakhla', city: 'Dakhla', icon: '📍' },
  { type: 'Ville', name: 'Ifrane', city: 'Ifrane', icon: '📍' },
  { type: 'Ville', name: 'Merzouga', city: 'Errachidia', icon: '📍' },
  { type: 'Ville', name: 'Aït Benhaddou', city: 'Ouarzazate', icon: '📍' },
];